### ISSUE TITLE
Removal has some issue

### ISSUE THREAD

**Issue by springjools** [springjools/deluge-autoremoveplus#1]
I use this to first pause torrents and then manually remove paused torrents from sonarr/lidarr/radarr. I guess people have dozens of different uses for this plugin. 

The removal or torrents/deleting torrents/data does work but it produces some error. I think the error somehow comes from the fact that something tries to delete the same torrent twice, and the second time is what causes the error and also makes deluge crash. The actual torrent is removed though, but not blacklisted to sonarr etc. The torrent state is also not updated so this still causes some future errors. Would be nice to fix this thing as well so that sonarr integration would work. Works using the command line.

**Comment by shadycuz** [comment]
I really like what you are doing but I'm wondering if the sonar/lidar/radar stuff should be a separate plugin?

Do you know if Deluge has some kinda event/msg bus that plugins can listen on and talk on? 

If so we could make this plugin msg out that a torrent was deleted, and then a dedicated plugin could hear that event and do X in sonar etc.


My use case for this plugin is just to keep my HDD from filling up and to make sure I seed X amount of time back.

**Comment by springjools** [comment]
I think deluge has its api that can talk to other plugins etc, but afaik, there is no method in sonarr et al to just blacklist an item -- it's done as an optional argument to the delete metod. I would love to do the work in sonarr instead, because it's better maintained, but only the download client has enough information about the status of the torrent, such as availability etc.

But go ahead and suggest a method if you like. I just followed how you manually do this thing. It's actually sonarr that manages the download client through the label (I think), so that's why the produre I impelmented mimics that. But I do agree it's convoluted.

**Comment by shadycuz** [comment]
@springjools What I mean is you should leave AutoRemovePlus to just removing torrents from deluge.

If you need another plugin for doing something to sonar etc then create a new plugin. 

Thats why I brought up the event bus, you could pass an event from AutoRemovePlus to a new plugin for sonar or w/e.

**Comment by springjools** [comment]
Yes but what you explain is not possible, because you cannot remove things twice

**Comment by ben-ba** [comment]
Why twice? AutoRemovePlus remove the torrent from deluge, then on remove a second plugin (the new one, shadycuz suggest) remove the torrent/movie/series from Sonarr,Radarr etc.

At the moment it should be possible to run a script (maybe mediaserver.py ;) ) with the included plugin "Execute" after a torrent get removed by hand or AutoRemovePlus.

**Comment by springjools** [comment]
Sure,if you find a way to also blacklist the release at the same time. From a sonarr et al point of view, that's necessary. Otherwise it will just download the same stuff again.

**Comment by springjools** [comment]
Now I have separated the removal and blacklisting so that blacklisting is done using the PVR api and removal is done locally.
