### ISSUE TITLE
Delete by time since last transfer

### ISSUE THREAD

**Issue by PeterAOBell** [springjools/deluge-autoremoveplus#11]
I would find it very useful to be able to remove torrents based on the length of time since last transfer.

Time since last transfer is shown in the torrent status in deluge v2+

**Comment by springjools** [comment]
Good idea! I agree.

**Comment by springjools** [comment]
I'm 90% done with this. It's not hard to add new filters, there are actually many more that could be added. But how to handle deluge 1.3.15, which I assume doesn't support this. That's what remains...

Here's a list of status functions:
https://git.deluge-torrent.org/deluge/tree/deluge/core/torrent.py#n1035

**Comment by PeterAOBell** [comment]
Really great news - thanks. I'm excited to see it in action!

**Comment by springjools** [comment]
https://github.com/springjools/deluge-autoremoveplus/releases

Tested it shortly and it seems to work. Report any issues as usual.
