### ISSUE TITLE
0.6.13 showing as 0.6.12 in deluge webui

### ISSUE THREAD

**Issue by maxwell-01** [springjools/deluge-autoremoveplus#19]
As the title says - minor thing but worth mentioning!
![Screenshot 2020-04-17 at 15 50 14](https://user-images.githubusercontent.com/45392468/79582083-338bcf00-80c3-11ea-8bef-c2b8eaa227be.png)
![Screenshot 2020-04-17 at 15 49 59](https://user-images.githubusercontent.com/45392468/79582084-34246580-80c3-11ea-873e-d8b7436ae305.png)

**Comment by springjools** [comment]
Yeah, I forget to change it there. Thanks. Will be fixed in next version.

**Comment by maxwell-01** [comment]
You're welcome - no dramas!
