### ISSUE TITLE
Error reading config

### ISSUE THREAD

**Issue by akang6** [springjools/deluge-autoremoveplus#2]
I'm getting this message in the logs:

> 17:45:39 [INFO    ][autoremoveplus.core           :295 ] AutoRemovePlus: check do_remove
> 17:45:39 [ERROR   ][autoremoveplus.core           :333 ] Error reading config: unorderable types: str() > float()

This is my config:

> {
>     "file": 1,
>     "format": 1
> }{
>     "api_lidarr": "",
>     "api_radarr": "",
>     "api_sonarr": "",
>     "count_exempt": false,
>     "enable_lidarr": false,
>     "enable_radarr": false,
>     "enable_sonarr": false,
>     "enabled": true,
>     "filter": "func_ratio",
>     "filter2": "func_seed_time",
>     "hdd_space": -1.0,
>     "interval": 0.02,
>     "label_rules": {},
>     "labels": [],
>     "max_seeds": 0,
>     "min": 1.0,
>     "min2": 7.0,
>     "pause_seed": false,
>     "remove": true,
>     "remove_data": true,
>     "rule_1_enabled": true,
>     "rule_2_enabled": true,
>     "seedtime_limit": "1447",
>     "seedtime_pause": "1447",
>     "sel_func": "or",
>     "server_url": "",
>     "tracker_rules": {},
>     "trackers": []
> }

**Comment by springjools** [comment]
Hi, I think this could be because of the empty string in "api_lidarr": "", I'll look into this.

**Comment by stokbaek** [comment]
Mine is doing a similar error, and it is not removing anything no matter how I set the rules.
Error:
```
[INFO    ][autoremoveplus.core           :69  ] AutoRemovePlus: check do_remove
[ERROR   ][autoremoveplus.core           :79  ] Error reading config: '>' not supported between instances of 'str' and 'float'
```
Config file:
```
{
    "file": 1,
    "format": 1
}{
    "count_exempt": false,
    "enable_lidarr": false,
    "enable_radarr": false,
    "enable_sonarr": false,
    "enabled": true,
    "filter": "func_ratio",
    "filter2": "func_seed_time",
    "hdd_space": -1.0,
    "interval": 0.009999999776482582,
    "label_rules": {},
    "labels": [],
    "max_seeds": 0,
    "min": 2.0,
    "min2": 240.0,
    "pause_seed": false,
    "remove": true,
    "remove_data": true,
    "rule_1_enabled": true,
    "rule_2_enabled": false,
    "seedtime_limit": "240",
    "seedtime_pause": "",
    "sel_func": "or",
    "tracker_rules": {},
    "trackers": []
}
```

**Comment by akang6** [comment]
I figured out what was happening. I removed the quotes from the seedtime_limit and seedtime_pause values in the config file and it stopped the errors:

`"seedtime_limit": "1447",
"seedtime_pause": "1447",`

Looks like the webui adds the quotes making it a string instead of a float.

**Comment by springjools** [comment]
Ok, super. Then that’s easy to fix. I’ll add some parsing to the stuff from the config file to prevent those errors, when i have the time.

**Comment by stokbaek** [comment]
After fixing that am I getting the following stacktrace
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/deluge/core/daemon_entry.py", line 122, in run_daemon
    daemon.start()
  File "/usr/lib/python3.8/site-packages/deluge/core/daemon.py", line 164, in start
    reactor.run()
  File "/usr/lib/python3.8/site-packages/twisted/internet/base.py", line 1283, in run
    self.mainLoop()
  File "/usr/lib/python3.8/site-packages/twisted/internet/base.py", line 1292, in mainLoop
    self.runUntilCurrent()
--- <exception caught here> ---
  File "/usr/lib/python3.8/site-packages/twisted/internet/base.py", line 913, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/usr/lib/python3.8/site-packages/deluge/config.py", line 468, in save
    loaded_data = json.loads(data[start:end])
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 34 column 23 (char 741)
```

**Comment by springjools** [comment]
Hmm, are you sure this error is related to autoremove plugin? I'm not familiar with python 3.8 as I only have 3.7 myself, but could it be compatibility with deluge itself that is the problem?
