### ISSUE TITLE
Plugin won't load in Docker installation

### ISSUE THREAD

**Issue by CoarsePiglet** [springjools/deluge-autoremoveplus#28]
Hello

The issue is simple: The plugin will not load.
I updated to the latest version of linuxserver/deluge and downloaded the latest release from here, uploaded it in Deluge but the plugin will not load.
I've tried restarting, removing config files, removing plugin folder...

My deluge version: 2.0.3-2-201906121747-ubuntu18.04.1 running in Docker on unRAID

Screenshots:
It won't load in the Plugins window after restarting, the .egg is in the plugins directory.
![2020 05 15 - 16 41 42](https://user-images.githubusercontent.com/6104954/82062896-14d12600-96cb-11ea-86c7-3fa711bb3563.png)

This is all it says about plugins when loading:

> 16:41:05 [INFO][deluge.core.daemon :154 ] Deluge daemon starting...
> 16:41:05 [INFO][deluge.pluginmanagerbase :189 ] Plugin AutoAdd enabled...
> 16:41:05 [INFO][deluge_label.core :78  ] *** Start Label plugin ***
> 16:41:05 [INFO][deluge.pluginmanagerbase :189 ] Plugin Label enabled...
> 16:41:05 [INFO][deluge.pluginmanagerbase :189 ] Plugin Scheduler enabled...

**Comment by CoarsePiglet** [comment]
Also when loading the .egg file I get this as result:
![2020 05 15 - 16 45 16](https://user-images.githubusercontent.com/6104954/82063182-75f8f980-96cb-11ea-9286-56042cb7de13.png)
And it'll create this file in my plugins directory when I click install:
![2020 05 15 - 16 45 41](https://user-images.githubusercontent.com/6104954/82063256-8ad58d00-96cb-11ea-87c1-6514e96b34f4.png)

**Comment by CoarsePiglet** [comment]
Update: I was able to load other plugins perfectly fine from placing the .egg in the plugins directory and rebooting

**Comment by mikkihugo** [comment]
Hi! This is a bug in Deluge webui itself.

See https://github.com/idlesign/deluge-webapi/issues/14

**Comment by springjools** [comment]
It should work by placing the .egg file in the plugins folder. If not, please provide logs from deluge.

As @mikkihugo wrote, I also experienced problems with the install script, but it's not that hard to manually put the file there.
