### ISSUE TITLE
Plugin won't start - binhex/arch-delugevpn - deluge 2.0.4dev20

### ISSUE THREAD

**Issue by staticn0de** [springjools/deluge-autoremoveplus#3]
The plugin is failing to load on deluge 2.0.4dev20 running in the binhex/arch-delugevpn docker container. The deluged.log file contains:

`08:17:46.651 [ERROR   ][deluge.pluginmanagerbase      :79  ] Unable to instantiate plugin 'AutoRemovePlus' from '/config/plugins/AutoRemovePlus.egg'!
08:17:46.652 [ERROR   ][deluge.pluginmanagerbase      :79  ] No module named 'past'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
    instance = cls(plugin_name.replace('-', '_'))
  File "/config/plugins/AutoRemovePlus.egg/autoremoveplus/__init__.py", line 48, in __init__
    from autoremoveplus.core import Core as _plugin_cls
  File "<frozen zipimport>", line 259, in load_module
  File "/config/plugins/AutoRemovePlus.egg/autoremoveplus/core.py", line 45, in <module>
    from past.utils import old_div
ModuleNotFoundError: No module named 'past'`

Seems to be a dependency issue with the python-future package

**Comment by springjools** [comment]
Yes, indeed. You would fix this with:
pip3 install future

But maybe that's not possible with a docker container, I'm not familiar with it unfortunately.

**Comment by stokbaek** [comment]
I made a temporary fixed image that has the future pip package installed    
`docker pull stokbaek/arch-delugevpn:2.0.3`

**Comment by aploleb** [comment]
> I made a temporary fixed image that has the future pip package installed
> `docker pull stokbaek/arch-delugevpn:2.0.3`

Hey mate,

do you think you could do the same for https://github.com/binhex/arch-deluge ? Appreciate if possible.

**Comment by springjools** [comment]
You mean add future as a dependency to this plugin? Maybe, I'll have a look.

**Comment by aploleb** [comment]
> You mean add future as a dependency to this plugin? Maybe, I'll have a look.

Is it possible to remove future as a dependancy? Its unusable on deluge containers as none of them use pip3 future.

**Comment by springjools** [comment]
The future package is a way of making the code compatible with both python 2 and 3. I guess deluge will soon drop python 2 support, and then these things can be rewritten.

But this page advises us to keep compatibility with both python versions: https://deluge.readthedocs.io/en/latest/devguide/how-to/update-1.3-plugin.html

**Comment by stokbaek** [comment]
> > I made a temporary fixed image that has the future pip package installed
> > `docker pull stokbaek/arch-delugevpn:2.0.3`
> 
> Hey mate,
> 
> do you think you could do the same for https://github.com/binhex/arch-deluge ? Appreciate if possible.

`docker pull stokbaek/arch-deluge:2.0.3`

**Comment by aploleb** [comment]
> The future package is a way of making the code compatible with both python 2 and 3. I guess deluge will soon drop python 2 support, and then these things can be rewritten.
> 
> But this page advises us to keep compatibility with both python versions: https://deluge.readthedocs.io/en/latest/devguide/how-to/update-1.3-plugin.html

Makes sense then. I will use stokbaek's docker container until that time then.



> > > I made a temporary fixed image that has the future pip package installed
> > > `docker pull stokbaek/arch-delugevpn:2.0.3`
> > 
> > 
> > Hey mate,
> > do you think you could do the same for https://github.com/binhex/arch-deluge ? Appreciate if possible.
> 
> `docker pull stokbaek/arch-deluge:2.0.3`

Thank you! Saves me a lot of headache. plugin working great now.

**Comment by staticn0de** [comment]
Binhex has updated the delugevpn container upstream but now I'm seeing:

`6:03:44.743 [ERROR   ][deluge.pluginmanagerbase      :79  ] No module named 'requests'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
    instance = cls(plugin_name.replace('-', '_'))
  File "/config/plugins/AutoRemovePlus-0.6.8-py3.8.egg/autoremoveplus/__init__.py", line 48, in __init__
    from autoremoveplus.core import Core as _plugin_cls
  File "<frozen zipimport>", line 259, in load_module
  File "/config/plugins/AutoRemovePlus-0.6.8-py3.8.egg/autoremoveplus/core.py", line 51, in <module>
    from .mediaserver import Mediaserver
  File "<frozen zipimport>", line 259, in load_module
  File "/config/plugins/AutoRemovePlus-0.6.8-py3.8.egg/autoremoveplus/mediaserver.py", line 24, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'`

Is there a list of modules that need to be installed for this plugin?

**Comment by torresdrew** [comment]
Same issue I am having.

**Comment by staticn0de** [comment]
I got it working by manually installing python requests. I’ve asked binhex to include it on the image. 

https://github.com/binhex/arch-delugevpn/issues/148

**Comment by torresdrew** [comment]
How did you manually install?

**Comment by springjools** [comment]
pip (or pip3) install requests

**Comment by springjools** [comment]
There probably should be a list of required packages, but I kinda rushed the release of this since everyone was in a rush. I'll see if I can rewrite some of this during the holiday break.

**Comment by torresdrew** [comment]
Can't use pip/pip3 I just get a command not found error.

**Comment by torresdrew** [comment]
pacman -S --needed python-requests --noconfirm got me what I needed!

**Comment by springjools** [comment]
It would also be possible to disable the api connection part if requests isn't present. Will look into this.

**Comment by staticn0de** [comment]
Binhex has fixed the delugevpn container by adding python-future and python-requests so AutoRemovePlus works as expected. Those of you using deluge instead of delugevpn from binhex, you can just pull down the delugevpn container and set the VPN enabled flag to no.

**Comment by exzacklyright** [comment]
Having an issue with the .egg install. Using delugevpn . Doesn't show up in Deluge after. 

https://i.imgur.com/HO1qAiv.png

Byte-compiling build/bdist.linux-x86_64/egg/autoremoveplus/gtkui.py to gtkui.cpython-38.pyc
  File "build/bdist.linux-x86_64/egg/autoremoveplus/gtkui.py", line 147
    def on_menu_show(menu, (menu_item, toggled)):
                           ^
SyntaxError: invalid syntax

byte-compiling build/bdist.linux-x86_64/egg/autoremoveplus/mediaserver.py to mediaserver.cpython-38.pyc
byte-compiling build/bdist.linux-x86_64/egg/autoremoveplus/webui.py to webui.cpython-38.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
