### ISSUE TITLE
Fix deprecated logging.

### ISSUE THREAD

**Issue by mhertz** [springjools/deluge-autoremoveplus#32]
Could you kindly please consider adding same change as the PR I just submitted against tote94's fork, thanks.

More info in the comment I made there, about why is important:

https://github.com/tote94/deluge-autoremoveplus/pull/2

Thanks in advance.

Edit: I just noticed you already include correct lines later, but that first initial deprecated line would still be nice to get removed, as will still trip up in unofficial deluge2 installer for windows, plus from what I've read, likely also when official installer emerges, as seemingly pyinstaller freezed exe's have same issue.

**Comment by springjools** [comment]
Yes, I'm also a bit confused as I thought I had already implemented this.

**Comment by springjools** [comment]
Ah, I just forgot to remove the internal importing of the deluge log module. Yes, I will make that fix.

I would also like to have the logging format include the date, currently it's just posting the time as hh:mm.sssss
