### ISSUE TITLE
Issue with thinclient without GUI open, fails trigger some events.

### ISSUE THREAD

**Issue by mhertz** [springjools/deluge-autoremoveplus#36]
As title, there's issue with this plugin, like tote94's fork likewise, because the usage of TorrentManager's get_status() deluge api-call returns cached libtorrent values by default, so please add 'update=True' to dynamic field requests of that call, thanks, as else needs GUI open to refresh these values, to correctly trigger conditions using such.

Thanks in advance.

https://forum.deluge-torrent.org/viewtopic.php?f=9&t=47243&p=233391#p233391

**Comment by springjools** [comment]
Hey,

Thanks for sorting this out for me. I thought someone else made a better plugin, and no one was using this.

Yea, i will make those edits.

Pontus

**Comment by mhertz** [comment]
You're very welcome, and thanks for the plugin! :)

I'm sure this is used still and I wouldn't necessarily say the alternative fork is apparently "better", rather just "different" in its functioning on finished torrents in bottom conditions, though has advantage of working GTKUI prefs page, but misses a bunch of fixes and features, like you stated when initially was published on the forum, as was based from old original and not newer forks.

Thank you for replying, appreciated :) I'll close this, as served it's purpose and so no need clutter this section with it anymore then. Thanks again. 

Martin.
