### ISSUE TITLE
Ticking Checkbox Automatically Unticks

### ISSUE THREAD

**Issue by roberestarkk** [springjools/deluge-autoremoveplus#4]
Trying to enable the plugin, I get the issue where ticking the checkbox appears to work until the preferences window is closed, but re-opening shows it ticked for a second and then it auto un-ticks.

Using Deluge Version 1.3.15

Will re-try later today with today's release and update.

I know this issue was mentioned in the omaralvarez repo in a random comment trail somewhere, but it's not here yet so here it is.

**Comment by harrytheeskimo** [comment]
This was due to lacking a couple of python module dependencies - as referenced in the deluged.log.

Adding python3-future and python3-requests to my Ubuntu-based container fixed this for me.

**Comment by roberestarkk** [comment]
Yes I saw that in the comment trail in the omaralvarez repo. Unfortunately I don't have that much control over my system, so I have to wait until the dependencies are bundled in. Hence the tracking issue.

**Comment by springjools** [comment]
Ok, could you provide the log, maybe some check can be added.

**Comment by roberestarkk** [comment]
Sure,
https://pastebin.com/m0M4mLMP

**Comment by springjools** [comment]
Yeah that's the future package that's missing. If you can manually install packages try:
pip3 install future.

Unfortunately the plugin can't yet run without that package but next year we (I) could rewrite it to do so. But that means dropping support for python 2.7.

**Comment by roberestarkk** [comment]
Yeah, they don't even have pip installed (or accessible to me) on the server, and I'm not 100% certain that I have access to a location on Deluge's path. 
I'm also pretty sure we're running python 2.7

What I think I've worked out now is that you can't just straight up include it in the package, so I'll take it up with the server guys.
Thanks for keeping the plugin alive!

**Comment by springjools** [comment]
But pip is included with python, starting from 2.7 I think. Try "pip3" or "python -m pip" too if that works.

See also https://stackoverflow.com/questions/9780717/bash-pip-command-not-found

We really should have a discord server, it would be much easier to troubleshoot these issues then...

**Comment by roberestarkk** [comment]
I didn't know the `python -m pip` trick, that got pip running :)
Still failed to install though, don't have permission to access xmlrpc, I also assume that Deluge is running in a docker container, so even installing in the local machine might not work out

**Comment by springjools** [comment]
Ok, I don't know how to fix this issue. I could rewrite the plugin to not use the future package, but then it will be compatible with python 3.6 and higher only. Because the future packae is used to have code that's compatible with borth versions of python. But most people are now moving away from python 2.7.

Could you try a docker container that inlcudes the future package? I know someone else had the same issue and they solved it by including this package in their docker container. I think it was called delugevpn or something.

**Comment by springjools** [comment]
Test the latest version is working: https://github.com/springjools/deluge-autoremoveplus/releases

**Comment by ethras** [comment]
I have the same problem using the latest version 6.11 with linuxserver/deluge (deluge v2.0.3) docker container

Update : fixed by install python3-requests manually

**Comment by springjools** [comment]
@roberestarkk Can you try the latest version and with manually having installed requests?

Requests is needed to communicate with sonarr et al
