### ISSUE TITLE
Season vs Episode distinction (seed times)

### ISSUE THREAD

**Issue by camjac251** [springjools/deluge-autoremoveplus#5]
I requested this feature on the original repo but it sadly didn't get implemented [omaralvarez/deluge-autoremoveplus/issues/33](https://github.com/omaralvarez/deluge-autoremoveplus/issues/33)

Would it be possible to allow for different seed times for different trackers and whether something is an episode or season? It could be done through file regex as well but sonarr api would help create less false positives.

So for example, an episode would have say 72 hours of seed time before being removed while a full season would have 5 days of seed time. Right now, all episodes and seasons have the same time.

**Comment by springjools** [comment]
This is certainly possible. Here is what my sonarr api outputs: https://pastebin.com/cvpjwTAp

I just didn't bother to export more fields than downloadID (which is the hash for torrents) and "id", which is what sonarr identifies the item with. But would it work to export e.g. file size and somethign related to quality and from that work out whether it's a season or a episode?

So basically there should be a similar flexible box option for seeding as there is for unfinished downloads? There is already some exemptions that can be added on the second tab...

**Comment by camjac251** [comment]
I was thinking of a regex if possible. Matching SxxExx with a numbering system. Usually seasons are named S01 or Season 1, while episodes almost always have S00E00 formatting. With just a size sorter, you might get false positives with 2160p files or small encodes.

**Comment by camjac251** [comment]
What does the api output show for a Season? I noticed that it only has episodes on that paste

**Comment by springjools** [comment]
I think this goes outside of the scope of deluge, and instead should be part of radarr or sonarr. That's what they do.
