### ISSUE TITLE
Compiled and installed, but on execution "No module names 'past'" error

### ISSUE THREAD

**Issue by Groodles** [springjools/deluge-autoremoveplus#6]
`15:52:00 [ERROR   ][deluge.pluginmanagerbase      :154 ] Unable to instantiate plugin 'AutoRemovePlus' from '/home/deluge/.config/deluge/plugins/AutoRemovePlus-0.6.6.egg'!
15:52:00 [ERROR   ][deluge.pluginmanagerbase      :1343] No module named 'past'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/deluge/pluginmanagerbase.py", line 148, in enable_plugin
    instance = cls(plugin_name.replace('-', '_'))
  File "/home/deluge/.config/deluge/plugins/AutoRemovePlus-0.6.6.egg/autoremoveplus/__init__.py", line 48, in __init__
    from autoremoveplus.core import Core as _plugin_cls
  File "/home/deluge/.config/deluge/plugins/AutoRemovePlus-0.6.6.egg/autoremoveplus/core.py", line 45, in <module>
    from past.utils import old_div
ModuleNotFoundError: No module named 'past'
`

**Comment by springjools** [comment]
Try:
pip3 install future

**Comment by Groodles** [comment]
10:27:06 [ERROR   ][autoremoveplus.core           :333 ] Error reading config: '>' not supported between instances of 'str' and 'float'

**Comment by springjools** [comment]
Try a newer release:
https://github.com/springjools/deluge-autoremoveplus/releases

**Comment by Groodles** [comment]
Ahh, didn't spot the later releases.  Thanks.

I cloned the Master branch and compiled that (assuming it to be latest) and it gave me V 0.6.6

Cheers

**Comment by springjools** [comment]
Sorry for that, was lazy and didn't push all the changes. Will do so now. I'll close this issue, but re-open it if necessary. In the long run, the future module should not be necessary, but for now it's needed as this has to support both python 2 and 3.
