### ISSUE TITLE
Error reading config: could not convert string to float: ''

### ISSUE THREAD

**Issue by aploleb** [springjools/deluge-autoremoveplus#7]
Error preventing removal. Not sure what to do.

Things I've tried:
Remove plugin and .conf files
Restart Deluge
Install Plugin fresh
Restart Deluge

Getting this error every time with latest version.

02:31:16.772 [INFO    ][deluge.pluginmanagerbase      :69  ] Plugin AutoRemovePlus enabled...
02:31:21.770 [INFO    ][autoremoveplus.core           :69  ] check interval loop starting
02:31:21.771 [INFO    ][autoremoveplus.core           :69  ] AutoRemovePlus: check do_remove
02:31:21.771 [ERROR   ][autoremoveplus.core           :79  ] Error reading config: could not convert string to float: ''

**Comment by springjools** [comment]
Hmmm, could you post more of the log...

Because there is nothing on line 79 in the latest version of the plugin. You must be using an older one...

**Comment by aploleb** [comment]
09:01:21.772 [INFO    ][autoremoveplus.core           :69  ] AutoRemovePlus: check do_remove
09:01:21.773 [ERROR   ][autoremoveplus.core           :79  ] Error reading config: could not convert string to float: ''
09:31:21.772 [INFO    ][autoremoveplus.core           :69  ] AutoRemovePlus: check do_remove
09:31:21.773 [ERROR   ][autoremoveplus.core           :79  ] Error reading config: could not convert string to float: ''
10:01:21.772 [INFO    ][autoremoveplus.core           :69  ] AutoRemovePlus: check do_remove
10:01:21.773 [ERROR   ][autoremoveplus.core           :79  ] Error reading config: could not convert string to float: ''
10:31:21.772 [INFO    ][autoremoveplus.core           :69  ] AutoRemovePlus: check do_remove
10:31:21.773 [ERROR   ][autoremoveplus.core           :79  ] Error reading config: could not convert string to float: ''
11:01:21.772 [INFO    ][autoremoveplus.core           :69  ] AutoRemovePlus: check do_remove
11:01:21.773 [ERROR   ][autoremoveplus.core           :79  ] Error reading config: could not convert string to float: ''
11:31:21.772 [INFO    ][autoremoveplus.core           :69  ] AutoRemovePlus: check do_remove
11:31:21.773 [ERROR   ][autoremoveplus.core           :79  ] Error reading config: could not convert string to float: ''

The Config doesn't have a line 79 either

here is my config:
{
    "file": 1,
    "format": 1
}{
    "count_exempt": false,
    "enable_lidarr": false,
    "enable_radarr": false,
    "enable_sonarr": false,
    "enabled": true,
    "filter": "func_ratio",
    "filter2": "func_added",
    "hdd_space": -1.0,
    "interval": 0.5,
    "label_rules": {},
    "labels": [],
    "max_seeds": 0,
    "min": 0.0,
    "min2": 5.0,
    "pause_seed": false,
    "remove": true,
    "remove_data": false,
    "rule_1_enabled": true,
    "rule_2_enabled": true,
    "seedtime_limit": "",
    "seedtime_pause": "",
    "sel_func": "and",
    "tracker_rules": {},
    "trackers": []
}

Im using 6.8

**Comment by springjools** [comment]
Hmm, no idea why this happens, but I would guess the reason is the "" on the following lines:
"seedtime_limit": "",
"seedtime_pause": "",

Could you try to change them to some numeric value? I think maybe if they are empry they are replaced with empty strings...

**Comment by springjools** [comment]
Try this release: https://github.com/springjools/deluge-autoremoveplus/releases/tag/0.6.9

**Comment by springjools** [comment]
Closing this issue because I think the new release fixes this. Re-open if necessary.
