### ISSUE TITLE
Remove should have an option to remove data

### ISSUE THREAD

**Issue by aploleb** [springjools/deluge-autoremoveplus#9]
> Remove after seedtime (hours)

 should have the option to also delete data on the disk. Add this feature, and I would say it's 100% towards my needs. 

Thank you for fixing the last error with 0.6.9

**Comment by springjools** [comment]
Good idea, I thought about this but thought there would be too many buttons. And I thought that who wants to remove the things that you have downloaded, but then I noticed that sonarr and radarr actually sometimes forget to clean up their downloads. 

I'll see if I can add this.

**Comment by springjools** [comment]
Added in 0.6.10. See **https://github.com/springjools/deluge-autoremoveplus/releases**
